# Generated by Django 2.0.4 on 2018-04-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('player1_score', models.IntegerField(blank=True, default=0)),
                ('player2_score', models.IntegerField(blank=True, default=0)),
                ('winner', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
