# Generated by Django 2.0.4 on 2018-04-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameround'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameround',
            options={'ordering': ['id']},
        ),
    ]
